name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Confugure
      run: mkdir build && cd build && cmake ..
    - name: make
      run: cd build && make
    - name: unit tests
      run: ./MyTests
