name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Cmake
      run: >
        mkdir build
        cd build
        cmake ..
    - name: make
      run: make -j4
    - name: unit tests
      run: ./MyTests
    - name: clean
      run: make clean
